services:
  javaApp:
    image: openjdk:27-ea-oraclelinux9
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
      - ./target/docker-java-jar-0.0.1-SNAPSHOT.jar :/app/app.jar

    entrypoint:
      ./javaEntrypoint.sh

  mongodb:
    image: mongo:latest
    container_name: cohappy-mongo
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
