services:
  javaApp:
    image: eclipse-temurin:21-jre-jammy
    ports:
      - "8080:8080"
    volumes:
      - ./backend-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: [
      "java", 
      "-jar", 
      "app.jar", 
      "--spring.data.mongodb.uri=mongodb://mongodb:27017/cohappy",
      "--spring.mongodb.uri=mongodb://mongodb:27017/cohappy"
    ]
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: cohappy-mongo
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
